version:"1"

services:
    php:
        build: .docker/php
        volumes:
            - ./:/var/www/html/weather-api
            - /var/log/apache2/weather-api:var/log/apache2
        ports:
            - '8000:80'
        environment:
            - VIRTUAL_HOST=weather-api

